USE PROYECTO;

DROP TABLE IF EXISTS ROL_INTERES;
DROP TABLE IF EXISTS INTERES_RECOMENDACION;
DROP TABLE IF EXISTS RECOMENDACION;
DROP TABLE IF EXISTS INTERES;
DROP TABLE IF EXISTS MINIATURA;
DROP TABLE IF EXISTS DETALLE;
DROP TABLE IF EXISTS DASHBOARD;
DROP TABLE IF EXISTS TOKEN;
DROP TABLE IF EXISTS TIPO;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS ROL;

CREATE TABLE ROL(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE USUARIO(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NICK VARCHAR(255) NOT NULL,
    MAIL VARCHAR(255) NOT NULL,
    PWD VARCHAR(255) NOT NULL,
    FECHA_REGISTRO DATE NOT NULL,
    FECHA_NACIMIENTO DATE,
    AVATAR VARCHAR(255) DEFAULT 'default.jpg',
    ROL_ID INT NOT NULL,
    FOREIGN KEY (ROL_ID) REFERENCES ROL(ID) ON DELETE CASCADE
);

CREATE TABLE TIPO(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION TEXT NOT NULL
);

CREATE TABLE TOKEN(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TOKEN VARCHAR(255) NOT NULL,
    FECHA_CREACION DATE NOT NULL,
    FECHA_EXPIRACION DATE NOT NULL,
    ID_TIPO INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    FOREIGN KEY (ID_TIPO) REFERENCES TIPO(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE
);

CREATE TABLE DETALLE(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    DESCRIPCION TEXT,
    FECHA DATE,
    MINIATURA VARCHAR(255) DEFAULT 'default.jpg',
    ID_USUARIO INT NOT NULL,
    GANCHO text,
    INTRO text,
    ENGAGE1 text,
    SETUP text,
    ENGAGE2 text,
    ENGAGE3 text,
    CLIMAX text,
    BAJADA text,
    DESENLACE text,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE
);

CREATE TABLE INTERES(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    DESCRIPCION TEXT NOT NULL
);

CREATE TABLE ROL_INTERES(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_ROL INT NOT NULL,
    ID_INTERES INT NOT NULL,
    FOREIGN KEY (ID_ROL) REFERENCES ROL(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_INTERES) REFERENCES INTERES(ID) ON DELETE CASCADE
);

