USE VIDMENTOR;

DROP TABLE IF EXISTS ROL_INTERES;
DROP TABLE IF EXISTS INTERES;
DROP TABLE IF EXISTS DETALLE;
DROP TABLE IF EXISTS TOKEN;
DROP TABLE IF EXISTS TIPO;
DROP TABLE IF EXISTS DIRECCION;
DROP TABLE IF EXISTS DATOS_PERSONALES;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS ROL;

CREATE TABLE ROL(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE,
	DESCRIPCION TEXT NOT NULL,
	PERMISOS INT DEFAULT 0
);

INSERT INTO ROL(NOMBRE, DESCRIPCION, PERMISOS) VALUES('ADMIN', 'Administrador', 1);
INSERT INTO ROL(NOMBRE, DESCRIPCION) VALUES('USUARIO', 'Usuario');
INSERT INTO ROL(NOMBRE, DESCRIPCION) VALUES('INFLUENCER', 'Influencer');

CREATE TABLE USUARIO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NICK VARCHAR(255) NOT NULL,
	MAIL VARCHAR(255) NOT NULL UNIQUE,
	PWD VARCHAR(255) NOT NULL,
	F_REG DATE NOT NULL DEFAULT CURRENT_DATE,
	AVATAR VARCHAR(255) DEFAULT 'default.jpg',
	OAUTH VARCHAR(255) DEFAULT NULL,
	ROL_ID INT NOT NULL,
	FOREIGN KEY (ROL_ID) REFERENCES ROL(ID) ON DELETE CASCADE
);

CREATE TABLE DATOS_PERSONALES(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(255) DEFAULT NULL,
	APELLIDO1 VARCHAR(255) DEFAULT NULL,
	APELLIDO2 VARCHAR(255) DEFAULT NULL,
	SEXO CHAR(2) DEFAULT NULL, -- M, F, NB
	F_NAC DATE DEFAULT NULL,
	ID_USUARIO INT NOT NULL,
	FIJO VARCHAR(255) DEFAULT NULL,
	MOVIL VARCHAR(255) DEFAULT NULL,
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE
);

CREATE TABLE DIRECCION(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	PAIS VARCHAR(255) DEFAULT NULL,
	PROVINCIA VARCHAR(255) DEFAULT NULL,
	LOCALIDAD VARCHAR(255) DEFAULT NULL,
	DIRECCION VARCHAR(255) DEFAULT NULL,
	CP VARCHAR(255) DEFAULT NULL,
	ID_USUARIO INT NOT NULL,
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE
);

CREATE TABLE TIPO(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPCION TEXT NOT NULL
);

INSERT INTO TIPO(NOMBRE, DESCRIPCION) VALUES('MAIL', 'Token para recuperar contraseña');
INSERT INTO TIPO(NOMBRE, DESCRIPCION) VALUES('REGISTRO', 'Token para confirmar registro');

CREATE TABLE TOKEN(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TOKEN VARCHAR(255) NOT NULL,
    F_CRE DATE NOT NULL,
    F_EXP DATE NOT NULL,
    ID_TIPO INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    FOREIGN KEY (ID_TIPO) REFERENCES TIPO(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE
);

CREATE TABLE DETALLE(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    DESCRIPCION TEXT,
    F_CRE DATE,
	F_MOD DATE,
    MINIATURA VARCHAR(255) DEFAULT 'default.jpg',
    ID_USUARIO INT NOT NULL,
    GANCHO TEXT,
    INTRO TEXT,
    ENGAGE1 TEXT,
    SETUP TEXT,
    ENGAGE2 TEXT,
    ENGAGE3 TEXT,
    CLIMAX TEXT,
    BAJADA TEXT,
    DESENLACE TEXT,
    IG_STORIES BOOLEAN DEFAULT FALSE,
    REEL_CLIPS BOOLEAN DEFAULT FALSE,
    SHARE_SOCIAL_MEDIA BOOLEAN DEFAULT FALSE,
    CHECK_COMMENTS BOOLEAN DEFAULT FALSE,
    CHECK_CTR BOOLEAN DEFAULT FALSE,
    CHANGE_THUMBNAIL_2 BOOLEAN DEFAULT FALSE,
    CHANGE_TITLE_2 BOOLEAN DEFAULT FALSE,
    CHANGE_THUMBNAIL_3 BOOLEAN DEFAULT FALSE,
    CHANGE_TITLE_3 BOOLEAN DEFAULT FALSE,
    CHANGE_THUMBNAIL_4 BOOLEAN DEFAULT FALSE,
    CHANGE_TITLE_4 BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE
);

CREATE TABLE INTERES(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    DESCRIPCION TEXT NOT NULL
);

INSERT INTO INTERES(NOMBRE, DESCRIPCION) VALUES('MINECRAFT', 'Juego de construcción y aventuras');
INSERT INTO INTERES(NOMBRE, DESCRIPCION) VALUES('FORTNITE', 'Juego de batalla real');
INSERT INTO INTERES(NOMBRE, DESCRIPCION) VALUES('AMONG US', 'Juego de misterio y traición');
INSERT INTO INTERES(NOMBRE, DESCRIPCION) VALUES('ROBLOX', 'Juego de creación y aventuras');

CREATE TABLE ROL_INTERES(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_ROL INT NOT NULL,
    ID_INTERES INT NOT NULL,
    FOREIGN KEY (ID_ROL) REFERENCES ROL(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_INTERES) REFERENCES INTERES(ID) ON DELETE CASCADE
);

INSERT INTO ROL_INTERES(ID_ROL, ID_INTERES) VALUES(2, 1);
INSERT INTO ROL_INTERES(ID_ROL, ID_INTERES) VALUES(2, 2);
INSERT INTO ROL_INTERES(ID_ROL, ID_INTERES) VALUES(2, 3);
INSERT INTO ROL_INTERES(ID_ROL, ID_INTERES) VALUES(2, 4);

DELIMITER $$


CREATE TRIGGER TRIGGER_INSERT_USUARIO
	AFTER INSERT ON USUARIO
	FOR EACH ROW
BEGIN
	INSERT INTO DATOS_PERSONALES (ID_USUARIO)
	VALUES (NEW.ID);
	INSERT INTO DIRECCION (ID_USUARIO)
	VALUES (NEW.ID);

END$$
DELIMITER ;

INSERT INTO USUARIO (NICK, MAIL, PWD, ROL_ID) VALUES('admin', 'admin@admin.dev', 'admin', 1);
INSERT INTO USUARIO (NICK, MAIL, PWD, ROL_ID) VALUES('usuario', 'usuario@usuario.dev', 'usuario', 2);
