USE VIDMENTOR;

DROP TABLE IF EXISTS ROL_INTERES;
DROP TABLE IF EXISTS INTERES_RECOMENDACION;
DROP TABLE IF EXISTS RECOMENDACION;
DROP TABLE IF EXISTS INTERES;
DROP TABLE IF EXISTS MINIATURA;
DROP TABLE IF EXISTS DETALLE;
DROP TABLE IF EXISTS DASHBOARD;
DROP TABLE IF EXISTS TOKEN;
DROP TABLE IF EXISTS TIPO;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS ROL;

CREATE TABLE `DETALLE` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(255) NOT NULL,
  `DESCRIPCION` text,
  `FECHA` date DEFAULT NULL,
  `MINIATURA` varchar(255) DEFAULT 'default.jpg',
  `ID_USUARIO` int NOT NULL,
  `GANCHO` text,
  `INTRO` text,
  `ENGAGE1` text,
  `SETUP` text,
  `ENGAGE2` text,
  `ENGAGE3` text,
  `CLIMAX` text,
  `BAJADA` text,
  `DESENLACE` text,
  `IG_STORIES` tinyint(1) DEFAULT '0',
  `REEL_CLIPS` tinyint(1) DEFAULT '0',
  `SHARE_SOCIAL_MEDIA` tinyint(1) DEFAULT '0',
  `CHECK_COMMENTS` tinyint(1) DEFAULT '0',
  `CHECK_CTR` tinyint(1) DEFAULT '0',
  `CHANGE_THUMBNAIL_2` tinyint(1) DEFAULT '0',
  `CHANGE_TITLE_2` tinyint(1) DEFAULT '0',
  `CHANGE_THUMBNAIL_3` tinyint(1) DEFAULT '0',
  `CHANGE_TITLE_3` tinyint(1) DEFAULT '0',
  `CHANGE_THUMBNAIL_4` tinyint(1) DEFAULT '0',
  `CHANGE_TITLE_4` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `ID_USUARIO` (`ID_USUARIO`),
  CONSTRAINT `DETALLE_ibfk_1` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIO` (`ID`) ON DELETE CASCADE
);

CREATE TABLE `INTERES` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(255) NOT NULL,
  `DESCRIPCION` text NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `ROL` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `ROL_INTERES` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ID_ROL` int NOT NULL,
  `ID_INTERES` int NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID_ROL` (`ID_ROL`),
  KEY `ID_INTERES` (`ID_INTERES`),
  CONSTRAINT `ROL_INTERES_ibfk_1` FOREIGN KEY (`ID_ROL`) REFERENCES `ROL` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `ROL_INTERES_ibfk_2` FOREIGN KEY (`ID_INTERES`) REFERENCES `INTERES` (`ID`) ON DELETE CASCADE
);

CREATE TABLE `TIPO` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(50) NOT NULL,
  `DESCRIPCION` text NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `TOKEN` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `TOKEN` varchar(255) NOT NULL,
  `FECHA_CREACION` date NOT NULL,
  `FECHA_EXPIRACION` date NOT NULL,
  `ID_TIPO` int NOT NULL,
  `ID_USUARIO` int NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `ID_TIPO` (`ID_TIPO`),
  KEY `ID_USUARIO` (`ID_USUARIO`),
  CONSTRAINT `TOKEN_ibfk_1` FOREIGN KEY (`ID_TIPO`) REFERENCES `TIPO` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `TOKEN_ibfk_2` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIO` (`ID`) ON DELETE CASCADE
);

CREATE TABLE `USUARIO` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NICK` varchar(255) NOT NULL,
  `MAIL` varchar(255) NOT NULL,
  `PWD` varchar(255) NOT NULL,
  `FECHA_REGISTRO` date NOT NULL,
  `FECHA_NACIMIENTO` date DEFAULT NULL,
  `AVATAR` varchar(255) DEFAULT 'default.jpg',
  `ROL_ID` int NOT NULL DEFAULT '2',
  `INTERES` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `ROL_ID` (`ROL_ID`),
  CONSTRAINT `USUARIO_ibfk_1` FOREIGN KEY (`ROL_ID`) REFERENCES `ROL` (`ID`) ON DELETE CASCADE
);